version: '2'
services:
  sa-apollo-proxy:
    image: diefrodriguezcha/sa_apollo_proxy
    depends_on:
      - sa-apollo-api
    ports:
      - "80:80"    
  sa-apollo-api:
    image: menoguera/sa_apollo_api
    environment:
      BOT_ENTRY: 'api/'
      BOT_PORT: '3000'
      CENTERS_ENTRY: 'courses-ms/resources/courses'
      CENTERS_PORT: '3001'
      NEWSLETTER_PORT: '3002'
      PORT: '5000'
      SHOW_URLS: 'true'
      URL: '35.229.96.221'
      USER_ENTRY: 'api/auth'
      USER_PORT: '3003'
    ports:
      -"5000:5000"
    depends_on:
      - sa-user-ms
      - sa-centers-ms
      - sa-news-ms    
  sa-user-ms:
    image: diefrodriguezcha/sa_user_ms
    environment:
      DOCKER_DEPLOY: 'true'
      PORT: '3003'
      SECRET: 'arquisoft'
      DATABASE: '27018'
    links:
    - sa-user-db        
  sa-user-db:
    image: mongo
    ports:
    - 27018:27018    
  sa-centers-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sa-centers-db
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: sa    
    ports:
      - "3307:3307"    
  sa-centers-ms:
    image: dulfrey/sa_centers_ms
    links:
    - sa-centers-db:sa-centers-db            
  sa-news-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: railsapp
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: appuser    
    ports:
      - "3306:3306"    
  sa-news-ms:
    image: menoguera/newsletter-api
    environment:
      DB_HOST: sa-news-db
      DB_NAME: railsapp
      DB_PASSWORD: password
      DB_USER: root
    volumes:
    - ./railsapp
    links:
    - sa-news-db:sa-news-db            